#!/usr/bin/env bash
set -euo pipefail

# Regenerate SHA256SUMS for main-branch distribution assets.
# Uses sha256sum if available, otherwise shasum -a 256.

ROOT="$(cd -- "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if command -v sha256sum >/dev/null 2>&1; then
  SHA=sha256sum
elif command -v shasum >/dev/null 2>&1; then
  SHA="shasum -a 256"
else
  echo "Need sha256sum or shasum" >&2
  exit 1
fi

echo "[checksums] computing..."
FILES=("install.sh" "verify.sh")

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

printf "# Generated by scripts/update_checksums.sh\n" > "$tmp"
for f in "${FILES[@]}"; do
  if [ ! -f "$f" ]; then
    echo "[checksums] skipping missing $f" >&2
    continue
  fi
  $SHA "$f" >> "$tmp"
done

mv "$tmp" "$ROOT/SHA256SUMS"
echo "[checksums] wrote SHA256SUMS"
